import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'CP Sports',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br" className="h-full bg-white">
      <body className="h-full">{children}</body>
    </html>
  )
}
